### ISSUE TITLE
Proper references

### ISSUE THREAD

**Issue by kevinzakka** [DMackRus/Franka-emika-panda-arm#1]
Upon reading the README, one would assume these XMLs were written by you from scratch but it would seem from the commits that they are taken from Menagerie? If the latter is true, would be great to make that more explicit!

**Comment by DMackRus** [comment]
Hi,

Definitely wasn't trying to imply these models were written by me, I think the old read me is from another repository when I first made this for my own research. I only have this repository publicly available so that if anyone wanted to try my other repository [TrajOptKP](https://github.com/DMackRus/TrajOptKP), they could easily have access to all the required models :)

I've updated the ReadME to properly convey that and give credit to where the models have come from :).
